# Generated by Django 3.1.6 on 2021-03-22 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='add_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_brand', models.CharField(max_length=100)),
                ('product_type', models.CharField(choices=[('1', 'Clothing'), ('2', 'Books'), ('3', 'Almirah'), ('4', 'Refrigerator'), ('5', 'Water Purifier'), ('6', 'Gas Stove'), ('7', 'Bed'), ('8', 'Mattress'), ('9', 'Chair'), ('10', 'Fan'), ('11', 'Item not in list')], max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=10000)),
                ('mobile_no', models.CharField(max_length=10)),
                ('product_img', models.ImageField(upload_to='images/')),
                ('product_img1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('product_img2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('product_img3', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('product_img4', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('material', models.CharField(blank=True, choices=[('1', 'Plastic'), ('2', 'Wood')], max_length=100, null=True)),
                ('drawers', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=100, null=True)),
                ('color', models.CharField(blank=True, choices=[('1', 'Red'), ('2', 'Blue'), ('3', 'Green'), ('4', 'Black'), ('5', 'White'), ('6', 'Yellow'), ('7', 'Violet'), ('8', 'Orange'), ('9', 'Purple')], max_length=100, null=True)),
                ('length', models.PositiveIntegerField(blank=True, null=True)),
                ('breadth', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('launch_year', models.DateField(blank=True, null=True)),
                ('weight', models.PositiveIntegerField(blank=True, null=True)),
                ('rent', models.PositiveIntegerField(blank=True, null=True)),
                ('duration', models.CharField(max_length=100, null=True)),
                ('door', models.CharField(blank=True, choices=[('1', '1'), ('2', '2')], max_length=100, null=True)),
                ('rating', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=100, null=True)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('burner', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=100, null=True)),
                ('stove_type', models.CharField(blank=True, choices=[('1', 'Gas'), ('2', 'Electric')], max_length=100, null=True)),
                ('mattress_material', models.CharField(blank=True, choices=[('1', 'Cotton'), ('2', 'Polyester'), ('3', 'Foam')], max_length=100, null=True)),
                ('bed_type', models.CharField(blank=True, choices=[('1', 'Single Bed'), ('2', 'Double Bed')], max_length=100, null=True)),
                ('storage', models.CharField(blank=True, choices=[('1', 'YES'), ('2', 'NO')], max_length=100, null=True)),
                ('with_mattress', models.CharField(blank=True, choices=[('1', 'YES'), ('2', 'NO')], max_length=100, null=True)),
                ('armrest', models.CharField(blank=True, choices=[('1', 'YES'), ('2', 'NO')], max_length=100, null=True)),
                ('foldable', models.CharField(blank=True, choices=[('1', 'YES'), ('2', 'NO')], max_length=100, null=True)),
                ('pack_of', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='seller_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_otp', models.CharField(max_length=4)),
                ('num_otp', models.CharField(max_length=4)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=200)),
                ('enterprise_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_otp', models.CharField(max_length=4)),
                ('mail_otp', models.CharField(max_length=4)),
                ('first_name', models.CharField(max_length=200)),
                ('Last_Name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
